--------------------------------------------------------
--  File created - czwartek-czerwiec-07-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HALA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."HALA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence KADRA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."KADRA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence KARTKI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."KARTKI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence KLUB_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."KLUB_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence LIGA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."LIGA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence MECZ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."MECZ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence TRENER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."TRENER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ZAWIESZENIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."ZAWIESZENIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ZAWODNICY_KADRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."ZAWODNICY_KADRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence ZAWODNIK_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PIOTR1"."ZAWODNIK_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table HALA
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."HALA" 
   (	"HALA_ID" NUMBER(10,0), 
	"NAZWA_HALI" VARCHAR2(255 BYTE), 
	"POJEMNOŒÆ" NUMBER(10,0), 
	"MIASTO" VARCHAR2(255 BYTE), 
	"KOD_POCZTOWY" NUMBER(10,0), 
	"ULICA" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KADRA
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."KADRA" 
   (	"KADRA_ID" NUMBER(10,0), 
	"MECZ_ID" NUMBER(10,0), 
	"ZAWODNIK_ID" NUMBER(10,0), 
	"KLUB_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KARTKI
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."KARTKI" 
   (	"KARTKA_ID" NUMBER(10,0), 
	"KOLOR_KARTKI" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table KLUB
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."KLUB" 
   (	"KLUB_ID" NUMBER(10,0), 
	"HALA_ID" NUMBER(10,0), 
	"KRAJ" VARCHAR2(255 BYTE), 
	"LIGA_ID" NUMBER(10,0), 
	"TRENER_ID" NUMBER(10,0), 
	"NAZWA_KLUBU" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LIGA
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."LIGA" 
   (	"LIGA_ID" NUMBER(10,0), 
	"NAZWA_LIGI" VARCHAR2(255 BYTE), 
	"POZIOM_LIGI" VARCHAR2(255 BYTE), 
	"ILOSC_ZESPO£OW" NUMBER(10,0), 
	"ILOSC_MECZY" NUMBER(10,0), 
	"ROK" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MECZ
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."MECZ" 
   (	"MECZ_ID" NUMBER(10,0), 
	"GOSC_KADRA" NUMBER(10,0), 
	"GOSPODARZ_KADRA" NUMBER(10,0), 
	"PKT_ZA_MECZ" NUMBER(10,0), 
	"FREKWENCJA" NUMBER(10,0), 
	"KOLEJKA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRENER
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."TRENER" 
   (	"TRENER_ID" NUMBER(10,0), 
	"IMIÊ" VARCHAR2(255 BYTE), 
	"NAZWISKO" VARCHAR2(255 BYTE), 
	"DATA_URODZENIA" DATE DEFAULT NULL, 
	"NARODOWOŒÆ" VARCHAR2(255 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAWIESZENIA
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."ZAWIESZENIA" 
   (	"ZAWIESZENIE_ID" NUMBER(10,0), 
	"DATA_ROZPOCZÊCIA" DATE, 
	"DATA_ZAKOÑCZENIA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAWODNICY_KADRY
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."ZAWODNICY_KADRY" 
   (	"KADRA_ID" NUMBER(10,0), 
	"ZAWODNIK_ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ZAWODNIK
--------------------------------------------------------

  CREATE TABLE "PIOTR1"."ZAWODNIK" 
   (	"ZAWODNIK_ID" NUMBER(10,0), 
	"KLUB_ID" NUMBER(10,0), 
	"IMIÊ" VARCHAR2(255 BYTE), 
	"NAZWISKO" VARCHAR2(255 BYTE), 
	"WIEK" NUMBER(10,0), 
	"WZROST" NUMBER(10,0), 
	"ZAWIESZENIE_ID" NUMBER(10,0), 
	"KARTKA_ID" NUMBER(10,0), 
	"PKT_ZDOBYTE" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PIOTR1.HALA
SET DEFINE OFF;
REM INSERTING into PIOTR1.KADRA
SET DEFINE OFF;
REM INSERTING into PIOTR1.KARTKI
SET DEFINE OFF;
REM INSERTING into PIOTR1.KLUB
SET DEFINE OFF;
REM INSERTING into PIOTR1.LIGA
SET DEFINE OFF;
REM INSERTING into PIOTR1.MECZ
SET DEFINE OFF;
REM INSERTING into PIOTR1.TRENER
SET DEFINE OFF;
REM INSERTING into PIOTR1.ZAWIESZENIA
SET DEFINE OFF;
REM INSERTING into PIOTR1.ZAWODNICY_KADRY
SET DEFINE OFF;
REM INSERTING into PIOTR1.ZAWODNIK
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index KADRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIOTR1"."KADRA_PK" ON "PIOTR1"."KADRA" ("KADRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index KLUB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIOTR1"."KLUB_PK" ON "PIOTR1"."KLUB" ("KLUB_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MECZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIOTR1"."MECZ_PK" ON "PIOTR1"."MECZ" ("MECZ_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ZAWODNIK_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PIOTR1"."ZAWODNIK_PK" ON "PIOTR1"."ZAWODNIK" ("ZAWODNIK_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table LIGA
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."LIGA" MODIFY ("LIGA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."LIGA" MODIFY ("NAZWA_LIGI" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."LIGA" MODIFY ("POZIOM_LIGI" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."LIGA" MODIFY ("ILOSC_ZESPO£OW" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."LIGA" MODIFY ("ILOSC_MECZY" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."LIGA" MODIFY ("ROK" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."LIGA" ADD PRIMARY KEY ("LIGA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAWODNICY_KADRY
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."ZAWODNICY_KADRY" MODIFY ("KADRA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNICY_KADRY" MODIFY ("ZAWODNIK_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MECZ
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."MECZ" MODIFY ("MECZ_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."MECZ" MODIFY ("GOSC_KADRA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."MECZ" MODIFY ("GOSPODARZ_KADRA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."MECZ" MODIFY ("PKT_ZA_MECZ" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."MECZ" MODIFY ("FREKWENCJA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."MECZ" MODIFY ("KOLEJKA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."MECZ" ADD CONSTRAINT "MECZ_PK" PRIMARY KEY ("MECZ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KADRA
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."KADRA" MODIFY ("KADRA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KADRA" MODIFY ("MECZ_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KADRA" MODIFY ("ZAWODNIK_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KADRA" MODIFY ("KLUB_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KADRA" ADD CONSTRAINT "KADRA_PK" PRIMARY KEY ("KADRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAWIESZENIA
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."ZAWIESZENIA" MODIFY ("ZAWIESZENIE_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWIESZENIA" MODIFY ("DATA_ROZPOCZÊCIA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWIESZENIA" MODIFY ("DATA_ZAKOÑCZENIA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWIESZENIA" ADD PRIMARY KEY ("ZAWIESZENIE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KARTKI
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."KARTKI" MODIFY ("KARTKA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KARTKI" MODIFY ("KOLOR_KARTKI" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KARTKI" ADD PRIMARY KEY ("KARTKA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HALA
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."HALA" MODIFY ("HALA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."HALA" MODIFY ("NAZWA_HALI" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."HALA" MODIFY ("POJEMNOŒÆ" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."HALA" MODIFY ("MIASTO" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."HALA" MODIFY ("KOD_POCZTOWY" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."HALA" MODIFY ("ULICA" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."HALA" ADD PRIMARY KEY ("HALA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZAWODNIK
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("ZAWODNIK_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("KLUB_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("IMIÊ" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("WIEK" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("WZROST" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("ZAWIESZENIE_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("KARTKA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" MODIFY ("PKT_ZDOBYTE" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."ZAWODNIK" ADD CONSTRAINT "ZAWODNIK_PK" PRIMARY KEY ("ZAWODNIK_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table KLUB
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."KLUB" MODIFY ("KLUB_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KLUB" MODIFY ("HALA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KLUB" MODIFY ("KRAJ" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KLUB" MODIFY ("LIGA_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KLUB" MODIFY ("TRENER_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KLUB" MODIFY ("NAZWA_KLUBU" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."KLUB" ADD CONSTRAINT "KLUB_PK" PRIMARY KEY ("KLUB_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRENER
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."TRENER" MODIFY ("TRENER_ID" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."TRENER" MODIFY ("IMIÊ" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."TRENER" MODIFY ("NAZWISKO" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."TRENER" MODIFY ("NARODOWOŒÆ" NOT NULL ENABLE);
  ALTER TABLE "PIOTR1"."TRENER" ADD PRIMARY KEY ("TRENER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KADRA
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."KADRA" ADD CONSTRAINT "KADRA_KLUB_FK1" FOREIGN KEY ("KLUB_ID")
	  REFERENCES "PIOTR1"."KLUB" ("KLUB_ID") ENABLE;
  ALTER TABLE "PIOTR1"."KADRA" ADD CONSTRAINT "KADRA_ZAWODNIK_FK1" FOREIGN KEY ("ZAWODNIK_ID")
	  REFERENCES "PIOTR1"."ZAWODNIK" ("ZAWODNIK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table KLUB
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."KLUB" ADD CONSTRAINT "KLUB_HALA_FK1" FOREIGN KEY ("HALA_ID")
	  REFERENCES "PIOTR1"."HALA" ("HALA_ID") ENABLE;
  ALTER TABLE "PIOTR1"."KLUB" ADD CONSTRAINT "KLUB_LIGA_FK1" FOREIGN KEY ("LIGA_ID")
	  REFERENCES "PIOTR1"."LIGA" ("LIGA_ID") ENABLE;
  ALTER TABLE "PIOTR1"."KLUB" ADD CONSTRAINT "KLUB_TRENER_FK1" FOREIGN KEY ("TRENER_ID")
	  REFERENCES "PIOTR1"."TRENER" ("TRENER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MECZ
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."MECZ" ADD CONSTRAINT "GOSC_KADRA" FOREIGN KEY ("GOSC_KADRA")
	  REFERENCES "PIOTR1"."KADRA" ("KADRA_ID") ENABLE;
  ALTER TABLE "PIOTR1"."MECZ" ADD CONSTRAINT "GOSPODARZ_KADRA" FOREIGN KEY ("GOSPODARZ_KADRA")
	  REFERENCES "PIOTR1"."KADRA" ("KADRA_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZAWODNICY_KADRY
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."ZAWODNICY_KADRY" ADD CONSTRAINT "ZAWODNICY_KADRY_KADRA_FK1" FOREIGN KEY ("KADRA_ID")
	  REFERENCES "PIOTR1"."KADRA" ("KADRA_ID") ENABLE;
  ALTER TABLE "PIOTR1"."ZAWODNICY_KADRY" ADD CONSTRAINT "ZAWODNICY_KADRY_ZAWODNIK_FK1" FOREIGN KEY ("KADRA_ID")
	  REFERENCES "PIOTR1"."ZAWODNIK" ("ZAWODNIK_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZAWODNIK
--------------------------------------------------------

  ALTER TABLE "PIOTR1"."ZAWODNIK" ADD CONSTRAINT "ZAWODNIK_KARTKI_FK1" FOREIGN KEY ("KARTKA_ID")
	  REFERENCES "PIOTR1"."KARTKI" ("KARTKA_ID") ENABLE;
  ALTER TABLE "PIOTR1"."ZAWODNIK" ADD CONSTRAINT "ZAWODNIK_KLUB_FK1" FOREIGN KEY ("KLUB_ID")
	  REFERENCES "PIOTR1"."KLUB" ("KLUB_ID") ENABLE;
  ALTER TABLE "PIOTR1"."ZAWODNIK" ADD CONSTRAINT "ZAWODNIK_ZAWIESZENIA_FK1" FOREIGN KEY ("ZAWIESZENIE_ID")
	  REFERENCES "PIOTR1"."ZAWIESZENIA" ("ZAWIESZENIE_ID") ENABLE;
--------------------------------------------------------
--  DDL for Trigger HALA_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."HALA_ON_INSERT" 
BEFORE INSERT ON HALA 
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.HALA_SEQ.nextval
  INTO: new.HALA_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."HALA_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KADRA_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."KADRA_ON_INSERT" 
BEFORE INSERT ON KADRA
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.KADRA_SEQ.nextval
  INTO: new.KADRA_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."KADRA_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KARTKI_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."KARTKI_ON_INSERT" 
BEFORE INSERT ON KARTKI
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.KARTKI_SEQ.nextval
  INTO: new.KARTKA_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."KARTKI_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KLUB_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."KLUB_ON_INSERT" 
BEFORE INSERT ON KLUB
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.KLUB_SEQ.nextval
  INTO: new.KLUB_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."KLUB_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LIGA_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."LIGA_ON_INSERT" 
BEFORE INSERT ON LIGA
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.LIGA_SEQ.nextval
  INTO: new.LIGA_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."LIGA_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MECZ_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."MECZ_ON_INSERT" 
BEFORE INSERT ON MECZ
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.MECZ_SEQ.nextval
  INTO: new.MECZ_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."MECZ_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TRENER_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."TRENER_ON_INSERT" 
BEFORE INSERT ON TRENER
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.TRENER_SEQ.nextval
  INTO: new.TRENER_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."TRENER_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ZAWIESZENIA_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."ZAWIESZENIA_ON_INSERT" 
BEFORE INSERT ON ZAWIESZENIA
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.ZAWIESZENIA_SEQ.nextval
  INTO: new.ZAWIESZENIE_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."ZAWIESZENIA_ON_INSERT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ZAWODNIK_ON_INSERT
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "PIOTR1"."ZAWODNIK_ON_INSERT" 
BEFORE INSERT ON ZAWODNIK
FOR EACH ROW 
BEGIN
  SELECT PIOTR1.ZAWODNIK_SEQ.nextval
  INTO: new.ZAWODNIK_ID
  FROM dual;
END;
/
ALTER TRIGGER "PIOTR1"."ZAWODNIK_ON_INSERT" ENABLE;
